import 'dotenv/config';
import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import mongoose from 'mongoose';
import { models, Profile, Vehicle, RideOffer, RideRequest, BikeRequest, Booking, CreditTransaction, Notification, CommunityEvent } from './src/models/index.js';
import { hashPassword, verifyPassword, signToken, authRequired } from './src/auth.js';
import { seedDatabase } from './src/seed.js';
import { userView, vehicleView, rideView, bookingView, walletView, lendingView, eventView } from './src/serializers.js';

if(!process.env.MONGODB_URI || !process.env.JWT_SECRET) { console.error('[Waymate] Missing MONGODB_URI or JWT_SECRET in backend/.env'); process.exit(1); }
const app=express(); app.use(helmet()); app.use(cors({origin:process.env.CLIENT_ORIGIN?.split(',').map(s=>s.trim())||true})); app.use(express.json({limit:'4mb'}));
const now=()=>new Date(); const id=p=>`${p}-${Date.now()}-${Math.random().toString(36).slice(2,8)}`;
async function contextFor(userId){
 const user=await Profile.findById(userId).lean(); if(!user) return null;
 const [vehicles,rides,bookings,rideRequests,bikeRequests,txs,notifications,events]=await Promise.all([
  Vehicle.find({owner_id:userId}).lean(), RideOffer.find({}).sort({departure_time:1}).lean(), Booking.find({$or:[{user_id:userId},{provider_id:userId}]}).sort({created_at:-1}).lean(),
  RideRequest.find({}).sort({created_at:-1}).lean(), BikeRequest.find({}).sort({created_at:-1}).lean(), CreditTransaction.find({user_id:userId}).sort({created_at:-1}).lean(),
  Notification.find({recipient_id:userId}).sort({created_at:-1}).lean(), CommunityEvent.find({}).sort({start_time:1}).lean()
 ]);
 const allProfiles=await Profile.find({}).lean(); const pMap=Object.fromEntries(allProfiles.map(p=>[p._id,p])); const vAll=await Vehicle.find({}).lean(); const vMap=Object.fromEntries(vAll.map(v=>[v._id,v]));
 const allRides=rides.map(r=>rideView(r,pMap[r.driver_id],vMap[r.vehicle_id]));
 return {user:userView(user), users:allProfiles.map(userView), vehicles:vAll.map(vehicleView), rides:allRides, bookings:bookings.map(b=>bookingView(b,pMap[b.provider_id],rMap.get(b.ride_offer_id),vMap[b.vehicle_id])), rideRequests:rideRequests.map(r=>({id:r._id,rideId:r.ride_offer_id,requesterId:r.requester_id,providerId:r.driver_id,seatsRequested:r.seats_requested,message:r.message,status:r.status,createdAt:new Date(r.created_at).getTime(),respondedAt:r.responded_at?new Date(r.responded_at).getTime():null,from:rMap.get(r.ride_offer_id)?.from,to:rMap.get(r.ride_offer_id)?.to,time:rMap.get(r.ride_offer_id)?.departureTime})), reviews:[], lending:bikeRequests.map(b=>lendingView(b,pMap[b.owner_id],pMap[b.requester_id],vMap[b.vehicle_id])), notifications:notifications.map(n=>({id:n._id,recipientId:n.recipient_id,senderId:n.sender_id,type:n.type,title:n.title,message:n.message,bookingId:n.booking_id,rideId:n.ride_offer_id,bike_request_id:n.bike_request_id,is_read:n.is_read,createdAt:new Date(n.created_at).getTime()})), events:events.map(eventView), wallet:walletView(user,txs), platformStats:await stats()};
}
async function stats(){ const [members,sharedRides,todayOffered,booked]=await Promise.all([Profile.countDocuments(),RideOffer.countDocuments({status:'ACTIVE'}),RideOffer.countDocuments({status:'ACTIVE',created_at:{$gte:new Date(new Date().setHours(0,0,0,0))}}),Booking.countDocuments({type:'PASSENGER',status:{$in:['UPCOMING','CONFIRMED']},created_at:{$gte:new Date(new Date().setHours(0,0,0,0))}})]); return {sharedRides:142+sharedRides,members,carbonSaved:14.8,todayBooked:booked,todayOffered,activeRequests:await RideRequest.countDocuments({status:'PENDING'})}; }
const rMap=new Map();
async function rebuildRideMap(){rMap.clear(); for(const r of await RideOffer.find({}).lean()) rMap.set(r._id,rideView(r,await Profile.findById(r.driver_id).lean(),r.vehicle_id?await Vehicle.findById(r.vehicle_id).lean():null));}
app.get('/api/health',(req,res)=>res.json({ok:true,service:'waymate-api',time:now().toISOString()}));
app.post('/api/auth/signup',async(req,res)=>{try{const b=req.body||{}; const email=String(b.email||'').trim().toLowerCase(); const username=String(b.username||'').trim().toLowerCase(); if(!email||!username||!b.password||!b.fullName) return res.status(400).json({message:'Name, username, email and password are required.'}); if(await Profile.findOne({$or:[{email},{username}]})) return res.status(409).json({message:'Email or username is already registered.'}); const userId=id('user'); const code=`WM-${1001+(await Profile.countDocuments())}`; const created=now(); const profile=await Profile.create({_id:userId,full_name:String(b.fullName).trim(),email,username,phone:String(b.phone||'').trim(),registration_number:String(b.registrationNumber||'').trim().toUpperCase(),college:b.college||'PVP Siddhartha Institute of Technology',community:b.college||'PVP Siddhartha Institute of Technology',pg_area:b.pgArea||'Campus Area',role:b.hasVehicle?'Provider + Passenger':'Passenger Account',avatar_url:b.avatar||`https://api.dicebear.com/9.x/initials/svg?seed=${encodeURIComponent(b.fullName)}`,trust_score:0,credits:100,created_at:created,updated_at:created,user_code:code,is_verified:false,verification_status:'PENDING',verification_step:'PENDING',rating:0,reviews_count:0,rides_completed:0,rides_shared:0,password_hash:await hashPassword(b.password),bike_number:b.vehicleRegistration||'',bike_colour:b.vehicleColour||'',fuel_type:b.isEv?'Electric':(b.fuelType||'Petrol'),is_ev:Boolean(b.isEv),vehicle_label:b.vehicleModel||'',reliability_score:'New member',mutual_connections:0,available_for_lending:false,college_domain:email.split('@')[1]||'waymate.app',primary_routes:[]}); if(b.hasVehicle&&b.vehicleModel){await Vehicle.create({_id:id('vehicle'),owner_id:userId,vehicle_type:'Two Wheeler',brand:String(b.vehicleModel).split(' ')[0]||'Generic',model:String(b.vehicleModel).trim(),registration_number:b.vehicleRegistration||'AP 16 TEMP',seats:1,is_available:true,created_at:created,updated_at:created,vehicle_colour:b.vehicleColour||'Standard',fuel_type:b.isEv?'Electric':(b.fuelType||'Petrol'),is_ev:Boolean(b.isEv),available_for_lending:false});} await CreditTransaction.create({_id:id('credit-tx'),user_id:userId,amount:100,transaction_type:'WELCOME_CREDIT',description:'Welcome to Waymate community credits',created_at:created}); const token=signToken(userId); await rebuildRideMap(); res.status(201).json({success:true,token,bootstrap:await contextFor(userId),userCount:await Profile.countDocuments()});}catch(e){console.error(e);res.status(500).json({message:'Unable to create account.'});}});
app.post('/api/auth/login',async(req,res)=>{try{const lookup=String(req.body?.emailOrUserId||'').trim().toLowerCase(); const u=await Profile.findOne({$or:[{email:lookup},{username:lookup},{user_code:lookup.toUpperCase()}]}); if(!u||!(await verifyPassword(req.body?.password,u.password_hash,u.user_code))) return res.status(401).json({message:'Email/Waymate ID/username or password is incorrect.'}); const token=signToken(u._id); await rebuildRideMap(); res.json({success:true,token,bootstrap:await contextFor(u._id),userCount:await Profile.countDocuments()});}catch(e){console.error(e);res.status(500).json({message:'Unable to log in.'});}});
app.get('/api/app/public',async(req,res)=>{try{const rides=await RideOffer.find({status:'ACTIVE'}).sort({departure_time:1}).lean(); const ps=await Profile.find({}).lean(); const vs=await Vehicle.find({}).lean(); const p=Object.fromEntries(ps.map(x=>[x._id,x])),v=Object.fromEntries(vs.map(x=>[x._id,x])); res.json({success:true,bootstrap:{user:null,users:ps.map(userView),vehicles:vs.map(vehicleView),rides:rides.map(r=>rideView(r,p[r.driver_id],v[r.vehicle_id])),bookings:[],rideRequests:[],reviews:[],lending:(await BikeRequest.find({status:'AVAILABLE'}).lean()).map(x=>lendingView(x,p[x.owner_id],p[x.requester_id],v[x.vehicle_id])),notifications:[],events:(await CommunityEvent.find({}).lean()).map(eventView),wallet:{balance:0,thisMonthEarned:0,thisMonthUsed:0,transactions:[]},platformStats:await stats()}});}catch(e){res.status(500).json({message:'Unable to load Waymate.'});}});
app.get('/api/app/bootstrap',authRequired,async(req,res)=>{try{await rebuildRideMap();res.json({success:true,bootstrap:await contextFor(req.userId)});}catch(e){console.error(e);res.status(500).json({message:'Unable to load your Waymate data.'});}});
app.put('/api/user/profile',authRequired,async(req,res)=>{try{const b=req.body||{},u=await Profile.findById(req.userId); if(!u)throw Object.assign(new Error('Profile not found.'),{status:404}); if(b.bikeColour!==undefined)u.bike_colour=String(b.bikeColour).trim();if(b.isEv!==undefined){u.is_ev=Boolean(b.isEv);u.fuel_type=u.is_ev?'Electric':(u.fuel_type||'Petrol');}if(b.vehicleModel!==undefined){u.vehicle_label=String(b.vehicleModel).trim();let v=await Vehicle.findOne({owner_id:u._id});if(v){v.model=u.vehicle_label;v.brand=u.vehicle_label.split(' ')[0]||v.brand;v.vehicle_colour=u.bike_colour;v.is_ev=u.is_ev;v.fuel_type=u.fuel_type;v.updated_at=now();await v.save();}}if(b.avatar)u.avatar_url=b.avatar;u.updated_at=now();await u.save();res.json({success:true,bootstrap:await contextFor(u._id)});}catch(e){res.status(500).json({message:'Unable to update profile.'});}});
app.post('/api/user/verify',authRequired,async(req,res)=>{try{await Profile.findByIdAndUpdate(req.userId,{$set:{is_verified:true,verification_status:'VERIFIED',verification_step:'VERIFIED',updated_at:now()}});res.json({success:true,bootstrap:await contextFor(req.userId)});}catch(e){res.status(500).json({message:'Verification update failed.'});}});
app.get('/api/rides',async(req,res)=>{try{const q={status:'ACTIVE'}; if(req.query.from)q.from_location={$regex:String(req.query.from),$options:'i'};if(req.query.to)q.to_location={$regex:String(req.query.to),$options:'i'};const rides=await RideOffer.find(q).sort({available_seats:-1,departure_time:1}).lean();const ps=await Profile.find({}).lean(),vs=await Vehicle.find({}).lean(),pm=Object.fromEntries(ps.map(x=>[x._id,x])),vm=Object.fromEntries(vs.map(x=>[x._id,x]));res.json({success:true,rides:rides.map(r=>rideView(r,pm[r.driver_id],vm[r.vehicle_id]))});}catch(e){res.status(500).json({message:'Unable to load rides.'});}});
app.post('/api/rides',authRequired,async(req,res)=>{try{const b=req.body||{},u=await Profile.findById(req.userId);let v=await Vehicle.findOne({owner_id:req.userId,is_available:true});if(!v&&b.vehicle){v=await Vehicle.create({_id:id('vehicle'),owner_id:req.userId,vehicle_type:'Two Wheeler',brand:String(b.vehicle).split(' ')[0],model:String(b.vehicle),registration_number:u.bike_number||'',seats:1,is_available:true,created_at:now(),updated_at:now(),vehicle_colour:u.bike_colour||'',fuel_type:u.fuel_type||'Petrol',is_ev:Boolean(u.is_ev),available_for_lending:false});}const dep=new Date(b.departureTimeISO||b.departureTime||now());const safeSeats=Math.max(1,Number(b.seatsTotal||1));const contribution=Number(b.contribution||Math.max(10,Math.round(Number(b.distanceKm||4.2)*3.2)));const ride=await RideOffer.create({_id:id('ride'),driver_id:req.userId,vehicle_id:v?._id||null,from_location:String(b.from||'').trim(),to_location:String(b.to||'').trim(),departure_time:dep,available_seats:safeSeats,credits_per_seat:contribution,notes:String(b.note||'').slice(0,400),status:'ACTIVE',created_at:now(),seats_total:safeSeats,distance_km:Number(b.distanceKm||4.2),requests_count:0});await Profile.findByIdAndUpdate(req.userId,{$inc:{rides_shared:1}});await rebuildRideMap();res.status(201).json({success:true,bootstrap:await contextFor(req.userId)});}catch(e){console.error(e);res.status(500).json({message:'Unable to publish ride.'});}});
app.post('/api/rides/:id/book',authRequired,async(req,res)=>{const session=await mongoose.startSession();try{await session.withTransaction(async()=>{const ride=await RideOffer.findById(req.params.id).session(session);const u=await Profile.findById(req.userId).session(session);const seats=Math.max(1,Number(req.body?.seats||1));if(!ride)throw Object.assign(new Error('Selected ride was not found.'),{status:404});if(ride.driver_id===req.userId)return res.status(400).json({message:'You cannot book your own ride.'});if(ride.available_seats<seats)return res.status(400).json({message:`Only ${ride.available_seats} seat(s) available.`});const cost=Number(ride.credits_per_seat||0)*seats;if(Number(u.credits||0)<cost){const er=new Error(`NOT ENOUGH COMMUNITY CREDITS. You need ${cost} credits for this ride. Your balance: ${u.credits||0} credits.`);er.status=402;throw er;}const dup=await Booking.findOne({ride_offer_id:ride._id,user_id:req.userId,status:{$in:['UPCOMING','CONFIRMED']}}).session(session);if(dup){const er=new Error('You have already reserved a seat on this journey.');er.status=409;throw er;}ride.available_seats-=seats;await ride.save({session});u.credits-=cost;u.rides_completed=(u.rides_completed||0)+1;await u.save({session});await CreditTransaction.create([{_id:id('credit-tx'),user_id:req.userId,amount:-cost,transaction_type:'RIDE_PAYMENT',description:`Ride booked — ${ride.from_location} → ${ride.to_location}`,ride_offer_id:ride._id,created_at:now()}],{session});await CreditTransaction.create([{_id:id('credit-tx'),user_id:ride.driver_id,amount:cost,transaction_type:'RIDE_EARNING',description:`Shared ride contribution from ${u.full_name}`,ride_offer_id:ride._id,created_at:now()}],{session});await Profile.findByIdAndUpdate(ride.driver_id,{$inc:{credits:cost}},{session});const bid=id('booking');await Booking.create([{_id:bid,user_id:req.userId,ride_offer_id:ride._id,vehicle_id:ride.vehicle_id,credits_paid:cost,status:'UPCOMING',created_at:now(),type:'PASSENGER',seats_booked:seats,provider_id:ride.driver_id,from_location:ride.from_location,to_location:ride.to_location,departure_time:ride.departure_time,partner_name:u.full_name,partner_avatar:u.avatar_url,partner_role:'Provider',contribution:cost}],{session});await Notification.create([{_id:id('notification'),recipient_id:ride.driver_id,sender_id:req.userId,type:'RIDE_BOOKED',title:'🔔 New ride request',message:`${u.full_name} requested a seat on your journey. ${ride.from_location} → ${ride.to_location}`,booking_id:bid,ride_offer_id:ride._id,is_read:false,created_at:now()}],{session});}); await rebuildRideMap();res.json({success:true,bootstrap:await contextFor(req.userId)});}catch(e){console.error(e);res.status(e.status||500).json({message:e.message||'Unable to book ride.',code:e.status===402?'INSUFFICIENT_CREDITS':'BOOKING_ERROR'});}finally{await session.endSession();}});
app.post('/api/bookings/:id/confirm',authRequired,async(req,res)=>{try{const b=await Booking.findById(req.params.id);if(!b)return res.status(404).json({message:'Booking not found.'});b.status='CONFIRMED';b.confirmed_at=now();await b.save();await Notification.create({_id:id('notification'),recipient_id:b.user_id,sender_id:req.userId,type:'RIDE_CONFIRMED',title:'✓ Ride confirmed',message:`Your seat on ${b.from_location} → ${b.to_location} is confirmed.`,booking_id:b._id,is_read:false,created_at:now()});res.json({success:true,bootstrap:await contextFor(req.userId)});}catch(e){res.status(500).json({message:'Unable to confirm booking.'});}});
app.post('/api/trips/:id/cancel',authRequired,async(req,res)=>{const s=await mongoose.startSession();try{await s.withTransaction(async()=>{const b=await Booking.findById(req.params.id).session(s);if(!b)throw Object.assign(new Error('Trip booking not found.'),{status:404});if(b.status==='CANCELLED')throw Object.assign(new Error('This trip is already cancelled.'),{status:400});b.status='CANCELLED';await b.save({session:s});if(b.type==='PASSENGER'){const ride=await RideOffer.findById(b.ride_offer_id).session(s);if(ride){ride.available_seats=Math.min(ride.seats_total||ride.available_seats+ b.seats_booked,ride.available_seats+b.seats_booked);await ride.save({session:s});}await Profile.findByIdAndUpdate(b.user_id,{$inc:{credits:b.credits_paid}},{session:s});await CreditTransaction.create([{_id:id('credit-tx'),user_id:b.user_id,amount:b.credits_paid,transaction_type:'RIDE_REFUND',description:`Refund for cancelled trip (${b.from_location} → ${b.to_location})`,ride_offer_id:b.ride_offer_id,created_at:now()}],{session:s});}});await rebuildRideMap();res.json({success:true,bootstrap:await contextFor(req.userId)});}catch(e){res.status(e.status||500).json({message:e.message||'Unable to cancel trip.'});}finally{await s.endSession();}});
app.get('/api/lending',authRequired,async(req,res)=>{try{const br=await BikeRequest.find({status:'AVAILABLE'}).lean();const ps=await Profile.find({}).lean(),vs=await Vehicle.find({}).lean(),pm=Object.fromEntries(ps.map(x=>[x._id,x])),vm=Object.fromEntries(vs.map(x=>[x._id,x]));res.json({success:true,lending:br.map(x=>lendingView(x,pm[x.owner_id],pm[x.requester_id],vm[x.vehicle_id]))});}catch(e){res.status(500).json({message:'Unable to load lending.'});}});
app.post('/api/lending/:vehicleId/request',authRequired,async(req,res)=>{try{const br=await BikeRequest.findOne({$or:[{_id:req.params.vehicleId},{vehicle_id:req.params.vehicleId}]});if(!br)return res.status(404).json({message:'Vehicle record not found.'});if(br.status!=='AVAILABLE')return res.status(400).json({message:'This vehicle is currently not available for lending.'});br.status='REQUESTED';br.requester_id=req.userId;br.borrow_purpose=String(req.body?.purpose||'College project supply pickup');br.created_at=now();await br.save();await Notification.create({_id:id('notification'),recipient_id:br.owner_id,sender_id:req.userId,type:'LENDING_REQUEST',title:'🔑 Vehicle lending request',message:'A community member requested your vehicle.',bike_request_id:br._id,is_read:false,created_at:now()});res.json({success:true,bootstrap:await contextFor(req.userId)});}catch(e){res.status(500).json({message:'Unable to request vehicle.'});}});
for(const [path,status] of [['approve','APPROVED'],['decline','AVAILABLE'],['handover','IN_USE'],['return','COMPLETED']]) app.post(`/api/lending/:vehicleId/${path}`,authRequired,async(req,res)=>{try{const br=await BikeRequest.findOne({$or:[{_id:req.params.vehicleId},{vehicle_id:req.params.vehicleId}]});if(!br)return res.status(404).json({message:'Lending record not found.'});br.status=status;if(status==='AVAILABLE'){br.requester_id=null;br.borrow_purpose=null;}await br.save();if(status==='COMPLETED'&&br.owner_id){const amount=Number(br.cost_credits||24);await Profile.findByIdAndUpdate(br.owner_id,{$inc:{credits:amount}});await CreditTransaction.create({_id:id('credit-tx'),user_id:br.owner_id,amount,transaction_type:'LENDING_EARNING',description:`Lending contribution for vehicle ${br.vehicle_id}`,bike_request_id:br._id,created_at:now()});}res.json({success:true,bootstrap:await contextFor(req.userId)});}catch(e){res.status(500).json({message:'Unable to update lending state.'});}});
function eventDateTime(dateLabel,time){const d=new Date();const label=String(dateLabel||'').trim().toLowerCase();if(label==='tomorrow')d.setDate(d.getDate()+1);else{const m=label.match(/(sep|oct|nov|dec|jan|feb|mar|apr|may|jun|jul|aug)[a-z]*\s+(\d{1,2})/i);if(m){const month=['jan','feb','mar','apr','may','jun','jul','aug','sep','oct','nov','dec'].indexOf(m[1].slice(0,3).toLowerCase());if(month>=0){d.setMonth(month);d.setDate(Number(m[2]));}}}const tm=String(time||'5:00 PM').match(/(\d{1,2}):(\d{2})\s*(AM|PM)?/i);if(tm){let h=Number(tm[1]);const ap=(tm[3]||'').toUpperCase();if(ap==='PM'&&h<12)h+=12;if(ap==='AM'&&h===12)h=0;d.setHours(h,Number(tm[2]),0,0);}return d;}
app.post('/api/events/create',authRequired,async(req,res)=>{try{const b=req.body||{}; const start=eventDateTime(b.date,b.time); const e=await CommunityEvent.create({_id:id('event'),title:String(b.title||'Campus Event').trim(),description:String(b.description||''),location:String(b.location||'').trim(),start_time:start,end_time:null,expected_attendance:Number(b.attendees||80),expected_demand:Number(b.expectedDemand||10),demand:b.demand||'Moderate',corridor:b.corridor||'',created_at:now()});res.json({success:true,bootstrap:await contextFor(req.userId),event:eventView(e)});}catch(e){res.status(500).json({message:'Unable to create event.'});}});
app.get('/api/notifications',authRequired,async(req,res)=>res.json({success:true,notifications:(await Notification.find({recipient_id:req.userId}).sort({created_at:-1}).lean()).map(n=>({id:n._id,recipientId:n.recipient_id,senderId:n.sender_id,type:n.type,title:n.title,message:n.message,bookingId:n.booking_id,rideId:n.ride_offer_id,bike_request_id:n.bike_request_id,is_read:n.is_read,createdAt:new Date(n.created_at).getTime()}))}));
app.post('/api/notifications/:id/read',authRequired,async(req,res)=>{await Notification.findOneAndUpdate({_id:req.params.id,recipient_id:req.userId},{is_read:true});res.json({success:true,bootstrap:await contextFor(req.userId)});});
app.post('/api/notifications/read-all',authRequired,async(req,res)=>{await Notification.updateMany({recipient_id:req.userId},{is_read:true});res.json({success:true,bootstrap:await contextFor(req.userId)});});
app.use((err,req,res,next)=>{console.error(err);res.status(500).json({message:'Waymate server error.'});});
const port=Number(process.env.PORT||5000);
await mongoose.connect(process.env.MONGODB_URI); console.log(`[Waymate] MongoDB connected: ${mongoose.connection.host}/${mongoose.connection.name}`); await seedDatabase(); console.log('[Waymate] Demo community data checked/seeded.'); await rebuildRideMap(); app.listen(port,'0.0.0.0',()=>console.log(`[Waymate] API running on http://localhost:${port}`));
