export function userView(u){ if(!u)return null; return { id:u._id, generatedUserId:u.user_code, username:u.username, name:u.full_name, email:u.email, phone:u.phone,
  collegeId:u.registration_number, college:u.college, community:u.community||u.college, pgArea:u.pg_area, role:u.role, avatar:u.avatar_url,
  isVerified:Boolean(u.is_verified), verificationStatus:u.verification_status||'PENDING', verificationStep:u.verification_step||'PENDING',
  trustLevel:u.trust_score>=4.8?'Trusted Member':u.reviews_count>0?'Developing Trust':'New Member', rating:Number(u.rating||0), reviewsCount:Number(u.reviews_count||0),
  ridesCompleted:Number(u.rides_completed||0), ridesShared:Number(u.rides_shared||0), vehicle:u.vehicle_label||'No vehicle registered', vehicleModel:u.vehicle_label||'',
  bikeNumber:u.bike_number||'', bikeColour:u.bike_colour||'', fuelType:u.fuel_type||'', isEv:Boolean(u.is_ev), availableForLending:Boolean(u.available_for_lending),
  reliabilityScore:u.reliability_score||'New member', mutualConnections:Number(u.mutual_connections||0), collegeDomain:u.college_domain||'waymate.app', walletBalance:Number(u.credits||0), primaryRoutes:u.primary_routes||[] }; }
export function vehicleView(v){return {id:v._id,ownerId:v.owner_id,vehicleType:v.vehicle_type,brand:v.brand,model:v.model,registrationNumber:v.registration_number,vehicleColour:v.vehicle_colour||'',fuelType:v.fuel_type||'',isEv:Boolean(v.is_ev),seats:Number(v.seats||1),availableForLending:Boolean(v.available_for_lending),isAvailable:v.is_available!==false};}
function displayDate(d){return d?new Date(d).toLocaleDateString('en-IN',{day:'2-digit',month:'short'}):'Today';}
function displayTime(d){return d?new Date(d).toLocaleTimeString('en-IN',{hour:'numeric',minute:'2-digit'}):'5:30 PM';}
export function rideView(r, provider, vehicle){return {id:r._id,providerId:r.driver_id,provider:userView(provider),from:r.from_location,to:r.to_location,date:'Today',departureTime:displayTime(r.departure_time),seatsTotal:Number(r.seats_total||r.available_seats||1),seatsAvailable:Number(r.available_seats||0),distanceKm:Number(r.distance_km||4.2),contribution:Number(r.credits_per_seat||0),vehicle:vehicle?`${vehicle.brand||''} ${vehicle.model||''}`.trim():(provider?.vehicle_label||'Two Wheeler'),vehicleColour:vehicle?.vehicle_colour||provider?.bike_colour||'',isEv:Boolean(vehicle?.is_ev??provider?.is_ev),fuelType:vehicle?.fuel_type||provider?.fuel_type||'',note:r.notes||'',status:r.status,requestsCount:Number(r.requests_count||0),createdAt:new Date(r.created_at).getTime()};}
export function bookingView(b, provider, ride, vehicle){return {id:b._id,rideId:b.ride_offer_id,userId:b.user_id,providerId:b.provider_id,type:b.type||'PASSENGER',from:b.from_location||ride?.from_location,to:b.to_location||ride?.to_location,date:'Today',time:displayTime(b.departure_time||ride?.departure_time),partnerName:b.partner_name||(provider?.full_name||'Community Member'),partnerAvatar:b.partner_avatar||(provider?.avatar_url||''),partnerRole:b.partner_role||'Provider',vehicle:b.vehicle|| (vehicle?`${vehicle.brand||''} ${vehicle.model||''}`.trim():'Two Wheeler'),seatsBooked:Number(b.seats_booked||1),contribution:Number(b.contribution||b.credits_paid||0),status:b.status,createdAt:new Date(b.created_at).getTime()};}
export function walletView(user, txs){const transactions=txs.map(t=>({id:t._id,type:t.amount<0?'USED':'EARNED',amount:Math.abs(Number(t.amount||0)),description:t.description,date:displayDate(t.created_at),timestamp:new Date(t.created_at).getTime(),rideId:t.ride_offer_id||undefined}));const earned=txs.filter(t=>t.amount>0).reduce((s,t)=>s+Number(t.amount),0),used=txs.filter(t=>t.amount<0).reduce((s,t)=>s+Math.abs(Number(t.amount)),0);return {balance:Number(user.credits||0),thisMonthEarned:earned,thisMonthUsed:used,transactions};}
export function lendingView(br,owner,requester,vehicle){return {id:br._id,vehicleId:br.vehicle_id,ownerId:br.owner_id,ownerName:owner?.full_name||'Vehicle Owner',ownerAvatar:owner?.avatar_url||'',isVerified:Boolean(owner?.is_verified),rating:Number(owner?.rating||0),vehicle:vehicle?`${vehicle.brand||''} ${vehicle.model||''}`.trim():'Two Wheeler',vehicleColour:vehicle?.vehicle_colour||'',bikeNumber:vehicle?.registration_number||'',fuelType:vehicle?.fuel_type||'',isEv:Boolean(vehicle?.is_ev),availableForLending:Boolean(vehicle?.available_for_lending),status:br.status,requesterId:br.requester_id||null,requesterName:requester?.full_name||null,requesterAvatar:requester?.avatar_url||null,requesterTrustLevel:requester?(requester.reviews_count>0?'Developing Trust':'New Member'):null,requesterRating:Number(requester?.rating||0),requesterReviewsCount:Number(requester?.reviews_count||0),requesterRidesCompleted:Number(requester?.rides_completed||0),requesterCollege:requester?.college||null,requesterCommunity:requester?.community||null,borrowPurpose:br.borrow_purpose||null,startTime:br.start_time?displayTime(br.start_time):'Available',endTime:br.end_time?displayTime(br.end_time):'',location:br.location||'',costCredits:Number(br.cost_credits||0),notes:br.message||'',updatedAt:new Date(br.created_at).getTime()};}
export function eventView(e){return {id:e._id,title:e.title,date:displayDate(e.start_time),time:displayTime(e.start_time),location:e.location,demand:e.demand||'Moderate',expectedDemand:Number(e.expected_demand||0),attendees:Number(e.expected_attendance||0),corridor:e.corridor||''};}
